name: C-Make CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      env:
          CC: gcc
          CXX: g++
          
  build-linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      env:
          CC: clang
          CXX: clang++

  build-linux-mingw:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install MinGW
      run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64
    - name: make
      run: make
      env:
          CC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++
  
  build-linux-gcc-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make debug
      env:
          CC: gcc
          CXX: g++
          
  build-linux-clang-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make debug
      env:
          CC: clang
          CXX: clang++

  build-linux-mingw-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install MinGW
      run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64
    - name: make
      run: make debug
      env:
          CC: x86_64-w64-mingw32-gcc
          CXX: x86_64-w64-mingw32-g++
